"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
from .base_settings import *

import dj_database_url

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ail0hx+l@10#g#8e--ps72fvjvn&m+9s&#8fgc=vo5%g275e^7'
DEBUG = True

ALLOWED_HOSTS = ['frostgrave-treasure.herokuapp.com']

DATABASES = {
    'default': dj_database_url.config()
}