# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostgrave', '0002_equipment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grimoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('grimoire_range', models.CharField(blank=True, max_length=255, null=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('defence', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('scroll_range', models.CharField(blank=True, max_length=255, null=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('defence', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='AdventurersGear',
        ),
        migrations.DeleteModel(
            name='Potion',
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trinket',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='trinket',
            old_name='school_magic',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='trinket',
            old_name='effect_description',
            new_name='effect',
        ),
        migrations.RenameField(
            model_name='trinket',
            old_name='uses',
            new_name='rarity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='item',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='trinket',
            name='visual_description',
        ),
        migrations.AddField(
            model_name='equipment',
            name='cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='effect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equip_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rarity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='use',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trinket',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trinket',
            name='use',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trinket',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EquipmentType',
        ),
    ]
